// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// ✅ VALIDAÇÃO CRÍTICA: Verificar se variáveis estão definidas
const validateEnvironment = () => {
  const errors: string[] = [];

  if (!SUPABASE_URL) {
    const msg = '❌ VITE_SUPABASE_URL não está definida. Configure no Vercel Dashboard → Environment Variables';
    console.error(msg);
    errors.push(msg);
  } else {
    console.log('✅ VITE_SUPABASE_URL:', `${SUPABASE_URL.substring(0, 30)}...`);
  }

  if (!SUPABASE_PUBLISHABLE_KEY) {
    const msg = '❌ VITE_SUPABASE_PUBLISHABLE_KEY (Chave Anónima) não está definida. Configure no Vercel Dashboard → Environment Variables';
    console.error(msg);
    errors.push(msg);
  } else {
    console.log('✅ VITE_SUPABASE_PUBLISHABLE_KEY:', `${SUPABASE_PUBLISHABLE_KEY.substring(0, 20)}...`);
  }

  if (errors.length > 0) {
    console.error('🔐 Supabase Configuration Errors:', errors);
    // Em produção, ainda criamos o cliente mas ele falhará nas queries
    // Isso permite que o app carregue e mostre erro ao usuário
  }
};

// Executar validação apenas uma vez no módulo
validateEnvironment();

// Log de debug (apenas em desenvolvimento)
if (import.meta.env.DEV) {
  console.log('🔐 Supabase Client Initialization:', {
    url: SUPABASE_URL ? '✅ Configured' : '❌ MISSING',
    publishableKey: SUPABASE_PUBLISHABLE_KEY ? '✅ Configured' : '❌ MISSING',
    environment: import.meta.env.MODE,
  });
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || '', // Fallback para string vazia se não definido
  SUPABASE_PUBLISHABLE_KEY || '', // Fallback para string vazia se não definido (Chave Anónima)
  {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);